// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Services').factory('Auth', [
    function() {
      var Auth;
      Auth = (function() {
        function Auth() {
          this.token = sessionStorage.authToken || false;
        }

        Auth.prototype.getAuthToken = function() {
          return this.token.toString();
        };

        Auth.prototype.setAuthToken = function(token) {
          return sessionStorage.authToken = this.token = token;
        };

        return Auth;

      })();
      return new Auth();
    }
  ]);

}).call(this);

//# sourceMappingURL=authentication.map
