// Generated by CoffeeScript 1.7.1
angular.module('Pyoopil.Directives').directive('classroom', [
  function() {
    return {
      restrict: 'A',
      scope: {
        classroom: '='
      },
      link: function(scope, elem, attrs) {
        if (scope.$parent.$last) {
          return scope.$emit('classroom.RENDER');
        }
      }
    };
  }
]);
