// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Global.Directives').directive('login', [
    'mainService', '$state', function(mainService, $state) {
      return {
        restrict: 'E',
        scope: {},
        templateUrl: '/pyoopil/js/app/partials/login.html',
        link: function(scope, elem, attrs, loginCtrl) {
          var $close, $form, $loginDialog, $resetPass;
          $loginDialog = elem.find('#dialog');
          $close = elem.find('a.close-link');
          $resetPass = elem.find('#for-pass');
          $form = elem.find('');
          scope.login = {};
          scope.submit = function(form) {
            var data, post;
            toastr.clear();
            if (form.email.$invalid) {
              toastr.error('Please enter a valid email');
              return;
            }
            if (form.password.$invalid) {
              toastr.error('Please enter a valid password');
              return;
            }
            if (form.$valid) {
              data = {
                'data[AppUser][email]': scope.login.email,
                'data[AppUser][password]': scope.login.password
              };
              post = mainService.postLogin(data);
              post.error(function() {
                return toastr.error('Login Failed !');
              });
            }
            return '';
          };
          elem.on('click', function() {
            scope.$parent.$emit('openModal');
            return $loginDialog.show();
          });
          $close.on('click', function(e) {
            scope.$parent.$emit('closeModal');
            $loginDialog.hide();
            return false;
          });
          return $resetPass.on('click', function() {
            e.preventDefault();
            scope.$parent.$emit('closeModal');
            $state.go('reset');
            return false;
          });
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=login.map
