// Generated by CoffeeScript 1.7.1
var App,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

App = window.App || {};

App.classrooms = App.classrooms || {};

(function($, window, document) {
  var AnnouncementViews;
  AnnouncementViews = (function() {
    function AnnouncementViews(elem) {
      this.newAnnouncement = __bind(this.newAnnouncement, this);
      this.renderAnnouncements = __bind(this.renderAnnouncements, this);
      this.init = __bind(this.init, this);
      this.$elem = elem;
      this.init();
    }

    AnnouncementViews.prototype.init = function() {
      this.announcementTemplate = Handlebars.compile(App.classrooms.templates.getTemplate('announcementTmpl'));
      return '';
    };

    AnnouncementViews.prototype.renderAnnouncements = function(e, announcements) {
      var announcement, announcementsHtml;
      announcementsHtml = (function() {
        var _i, _len, _results;
        if (announcements != null) {
          _results = [];
          for (_i = 0, _len = announcements.length; _i < _len; _i++) {
            announcement = announcements[_i];
            _results.push(this.renderAnnouncement(announcement));
          }
          return _results;
        }
      }).call(this);
      this.$elem.append(announcementsHtml);
      return this.$elem.trigger('Announcements.RENDER', true);
    };

    AnnouncementViews.prototype.renderAnnouncement = function(announcement) {
      var announcementHtml;
      if (announcement.hasOwnProperty('data')) {
        announcementHtml = this.announcementTemplate(announcement.data);
      } else {
        announcementHtml = this.announcementTemplate(announcement);
      }
      return announcementHtml;
    };

    AnnouncementViews.prototype.newAnnouncement = function(e, announcement) {
      var quizDialog;
      this.$createForm.dialog("close");
      quizDialog = this.quizDialogTemplate(classroom.data);
      this.$quizDialog.html(quizDialog);
      $('.ui-widget-overlay').addClass('custom-overlay');
      this.$quizDialog.dialog("open");
      this.$elem.prepend(this.renderClassroom(classroom));
      return this.$elem.trigger('Classrooms.RENDER', false);
    };

    return AnnouncementViews;

  })();
  return App.classrooms.announcementViews = AnnouncementViews;
})($, window, document);
