// Generated by CoffeeScript 1.7.1
var App,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

App = window.App || {};

App.classrooms = App.classrooms || {};

(function($, window, document) {
  var Views;
  Views = (function() {
    function Views(elem) {
      this.newJoin = __bind(this.newJoin, this);
      this.newClassroom = __bind(this.newClassroom, this);
      this.renderClassrooms = __bind(this.renderClassrooms, this);
      this.$elem = $(elem);
      this.$createForm = $("#create-assign");
      this.$quizDialog = $('#quizdialog');
      this.classroomTemplate = Handlebars.compile(App.classrooms.templates.getTemplate('classroomTile'));
      this.quizDialogTemplate = Handlebars.compile(App.classrooms.templates.getTemplate('quizTmpl'));
    }

    Views.prototype.renderClassrooms = function(e, classrooms) {
      var classroom, _i, _len, _results;
      if (classrooms != null) {
        _results = [];
          classrooms = classrooms.reverse();
        for (_i = 0, _len = classrooms.length; _i < _len; _i++) {
          classroom = classrooms[_i];
          _results.push(this.renderClassroom(classroom));
        }
        return _results;
      } else {
        return 'No Classroom Data';
      }
    };

    Views.prototype.renderClassroom = function(classroom) {
      var classroomHtml;
      if (classroom.hasOwnProperty('data')) {
        classroomHtml = this.classroomTemplate(classroom.data);
      } else {
        classroomHtml = this.classroomTemplate(classroom);
      }
      return this.$elem.prepend(classroomHtml);
    };

    Views.prototype.newClassroom = function(e, classroom) {
      var quizDialog;
      this.$createForm.dialog("close");
      quizDialog = this.quizDialogTemplate(classroom.data);
      this.$quizDialog.html(quizDialog);
      $('.ui-widget-overlay').addClass('custom-overlay');
      return this.$quizDialog.dialog("open");
    };

    Views.prototype.newJoin = function(e, classroom) {
      $(".newjoin").show();
      return $(".accessclass").hide();
    };

    return Views;

  })();
  return App.classrooms.views = new Views('#classrooms');
})($, window, document);
