// Generated by CoffeeScript 1.7.1
var App,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

App = window.App || {};

App.classrooms = App.classrooms || {};

(function($, window, document) {
  var $document, Discussion;
  $document = $(document);
  Discussion = (function() {
    function Discussion() {
      this.newDiscussion = __bind(this.newDiscussion, this);
      this.handleFileUpload = __bind(this.handleFileUpload, this);
      this.init = __bind(this.init, this);
    }

    Discussion.prototype.init = function(elem) {
      this.$elem = $(elem);
      this.services = App.classrooms.discussionServices;
      this.views = new App.classrooms.discussionViews(this.$elem);
      this.notifier = App.common.notifier;
      this.setEventListeners();
      return this.getDiscussions();
    };

    Discussion.prototype.getDiscussions = function() {
      var promise;
      promise = this.services.getDiscussions();
      return promise.then((function(_this) {
        return function(data) {
          if (_this.services.isValid(data) === true) {
            return $document.trigger('Discussions.UPDATE', [data]);
          } else {
            return _this.notifier.notify('error', 'No Discussions found');
          }
        };
      })(this));
    };

    Discussion.prototype.setEventListeners = function() {
      $document.on('Discussions.UPDATE', this.views.renderDiscussions);
      $document.on('Discussions.CREATE', this.views.newDiscussion);
      $document.on('Discussions.REPLY', this.views.newReply);
      $('#fileupload').on('change', this.handleFileUpload);
      $("#DiscussionAddForm, #DiscussionAddFormPoll, #DiscussionAddFormNote").on('submit', this.newDiscussion);
      this.$elem.on('submit', '.reply', this.newReply);
      $(".disc-submit-btn").click(function() {
        return $("#DiscussionAddForm").submit();
      });
      $(".disc-submit-btn-poll").click(function() {
        return $("#DiscussionAddFormPoll").submit();
      });
      $(".disc-submit-btn-note").click(function() {
        CKEDITOR.instances.editor1.updateElement();
        return $("#DiscussionAddFormNote").submit();
      });
      return this.$elem.on('click', '.praise li a', function(e) {
        var $parent, $that, id, praise, promise, that;
        that = this;
        $that = $(this);
        $parent = $that.closest('.praise');
        id = '';
        switch ($parent.data('type')) {
          case 'Discussion':
            id = $parent.data('discussion-id');
            break;
          case 'Reply':
            id = $parent.data('reply-id');
        }
        praise = {
          type: $parent.data('type'),
          id: id,
          vote: $that.data('praise-type')
        };
        promise = App.classrooms.discussionServices.setGamification(praise);
        promise.then(function(data) {
          if (data.status === false) {
            App.common.notifier.notify('error', data.message);
            return;
          }
          if (App.classrooms.services.isValid([data]) === true) {
            return App.common.notifier.notify('success', 'Your have successfully Voted');
          } else {
            return App.common.notifier.notify('error', 'Voting failed');
          }
        }, function(error) {
          return App.common.notifier.notify('error', 'Voting not success');
        });
        return false;
      });
    };

    Discussion.prototype.handleFileUpload = function(e) {
      this.uploadedFiles = e.target.files;
      return $('.files').html(this.uploadedFiles[0].name);
    };

    Discussion.prototype.newDiscussion = function(e) {
      var $form, ajax, form, formData;
      e.preventDefault();
      e.stopPropagation();
      form = e.target;
      $form = $(e.target);
      if (this.services.isValid(this.uploadedFiles)) {
        formData = new FormData();
        $.each(this.uploadedFiles, function(key, value) {
          return formData.append(key, value);
        });
      }
      ajax = App.classrooms.discussionServices.newDiscussion(form);
      return ajax.done(function(data) {
        console.log(data);
        form.reset();
        $form.find('.cnl-btn').click();
        if (data.status === false) {
          App.common.notifier.notify('error', data.message);
          return;
        }
        if (App.classrooms.services.isValid([data]) === true) {
          App.common.notifier.notify('success', 'Your have successfully Created a new Discussion');
          return $document.trigger('Discussions.CREATE', data.data);
        } else {
          return App.common.notifier.notify('error', 'New Discussion Creation failed');
        }
      });
    };

    Discussion.prototype.newReply = function(e) {
      var $form, $parent, $parentClass, form, promise;
      e.preventDefault();
      e.stopPropagation();
      form = e.target;
      $form = $(e.target);
      $parent = $form.closest('.discussion');
      $parentClass = '.discussion_' + $parent.data('discussion-id');
      promise = App.classrooms.discussionServices.addReply($form);
      return promise.then(function(data) {
        if (data.status === false) {
          App.common.notifier.notify('error', data.message);
          return;
        }
        if (App.classrooms.services.isValid([data]) === true) {
          App.common.notifier.notify('success', 'Your have successfully Replied to this Discussion');
          form.reset();
          return $document.trigger('Discussions.REPLY', {
            "data": data.data,
            "parentClass": $parentClass
          });
        } else {
          return App.common.notifier.notify('error', 'Reply failed');
        }
      });
    };

    return Discussion;

  })();
  return App.classrooms.discussion = new Discussion();
})($, window, document);
