// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Global.Services').factory('mainService', [
    '$http', '$window', '$q', 'Auth', function($http, $window, $q, Auth) {
      var mainService;
      mainService = (function() {
        var self;

        self = mainService;

        function mainService() {
          self.url = $window.location.origin + $window.location.pathname;
        }

        mainService.prototype.postData = function(url, data, isLogin) {
          var headers, xhr;
          if (isLogin) {
            headers = '';
          } else {
            headers = {
              'Authorization': Auth.getAuthToken()
            };
          }
          xhr = $http({
            method: 'POST',
            url: url,
            data: data,
            headers: headers
          });
          return xhr;
        };

        mainService.prototype.getData = function(url) {
          var xhr;
          xhr = $http({
            method: 'GET',
            url: url,
            headers: {
              'X-AuthTokenHeader': Auth.getAuthToken()
            }
          });
          return xhr;
        };

        mainService.prototype.postLogin = function(data) {
          var url;
          url = self.url + 'login';
          return this.postData(url, data, true);
        };

        mainService.prototype.postRegistration = function(data) {
          var d;
          d = $q.defer();
          d.resolve();
          return d.promise;
        };

        mainService.prototype.newClassroom = function(data) {
          var url;
          return url = self.url + 'add.json';
        };

        mainService.prototype.getClassrooms = function() {
          var url;
          url = self.url + 'Classrooms/getclassrooms.json?page=1';
          return this.getData(url);
        };

        return mainService;

      })();
      return new mainService();
    }
  ]);

}).call(this);

//# sourceMappingURL=mainService.map
