// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Global.Controllers').controller('mainCtrl', [
    '$scope', 'Utilities', 'mainService', 'Auth', '$state', function($scope, Utilities, mainService, Auth, $state) {
      $scope.template = {};
      $scope.showModal = false;
      $scope.classroom = {};
      Utilities.init($scope);
      return $scope.newClassroom = function() {
        if ($scope.classroom.name == null) {
          toastr.error('Enter a classroom Name');
          return;
        }
        if ($scope.classroom.type == null) {
          toastr.error('Enter a classroom Type');
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=mainCtrl.map
