// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Directives').controller('loginCtrl', [
    '$scope', function($scope) {
      this.closeModal = function() {
        return $scope.$parent.$emit('closeModal');
      };
      return '';
    }
  ]).directive('login', [
    'mainService', '$state', 'Auth', function(mainService, $state, Auth) {
      return {
        restrict: 'E',
        scope: {},
        controller: 'loginCtrl',
        templateUrl: 'js/app/partials/login.html',
        link: function(scope, elem, attrs, loginCtrl) {
          var $close, $form, $loginDialog, $resetPass;
          $loginDialog = elem.find('#dialog');
          $close = elem.find('a.close-link');
          $resetPass = elem.find('#for-pass');
          $form = elem.find('');
          scope.login = {};
          scope.submit = function(form) {
            var data, post;
            toastr.clear();
            if (form.email.$invalid) {
              toastr.error('Please enter a valid email');
              return;
            }
            if (form.password.$invalid) {
              toastr.error('Please enter a valid password');
              return;
            }
            if (form.$valid) {
              data = {
                "AppUser": {
                  "email": scope.login.email,
                  "password": scope.login.password
                }
              };
              post = mainService.postLogin(data);
              post.then(function(data) {
                if (data.data.status === true) {
                  loginCtrl.closeModal();
                  Auth.setAuthToken(data.data.data['auth_token']);
                  return $state.go('login.Classrooms');
                } else {
                  return toastr.error('Login Failed !');
                }
              }, function() {
                return toastr.error('Login Failed !');
              });
            }
            return '';
          };
          elem.on('click', function() {
            scope.$parent.$emit('openModal');
            return $loginDialog.show();
          });
          $close.on('click', function(e) {
            scope.$parent.$emit('closeModal');
            $loginDialog.hide();
            return false;
          });
          return $resetPass.on('click', function(e) {
            e.preventDefault();
            scope.$parent.$emit('closeModal');
            $state.go('reset');
            return false;
          });
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=login.map
