// Generated by CoffeeScript 1.7.1
var App,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

App = window.App || {};

App.LeftNavScroll = App.LeftNavScroll || {};

(function($, window, document) {
  var Views;
  Views = (function() {
    function Views(elem) {
      this.renderClassrooms = __bind(this.renderClassrooms, this);
      var al, bh;
      this.$elem = $(elem);
      this.$classroomsContainer = $('div.scroll-pane');
      this.classrooms = [];
      bh = $(window).height();
      al = bh - 260;
      this.$classroomsContainer.css({
        'height': +al + 'px'
      });
      this.template = Handlebars.compile(App.LeftNavScroll.templates.getTemplate('classroomTile'));
      $('.hassub').hover(function() {
        $(".container").addClass("show-sub");
        return $(this).addClass("hover");
      }, function() {
        $(".container").removeClass("show-sub");
        return $(this).removeClass("hover");
      });
    }

    Views.prototype.renderClassrooms = function(e, classrooms) {
      var classroom, _i, _len, _ref;
      if (classrooms != null) {
        this.classrooms = _.union(this.classrooms, classrooms);
        this.$classroomsContainer.empty();
        _ref = this.classrooms;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          classroom = _ref[_i];
          this.renderClassroom(classroom);
        }
      } else {
        return 'No Classroom Data';
      }
      return this.$classroomsContainer.each(function() {
        return setSlider($(this));
      });
    };

    Views.prototype.renderClassroom = function(classroom) {
      var classroomHtml;
      if (classroom.hasOwnProperty('data')) {
        classroomHtml = this.template(classroom.data);
      } else {
        classroomHtml = this.template(classroom);
      }
      return this.$classroomsContainer.prepend(classroomHtml);
    };

    return Views;

  })();
  return App.LeftNavScroll.views = new Views('.sub');
})($, window, document);
