// Generated by CoffeeScript 1.7.1
var App,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

App = window.App || {};

App.classrooms = App.classrooms || {};

(function($, window, document) {
  var Configs;
  Configs = (function() {
    function Configs() {
      this.getResourcePath = __bind(this.getResourcePath, this);
    }

    Configs.prototype.getBaseUrl = function() {
      return 'js/app/';
    };

    Configs.prototype.getResourcePath = function() {
      var resource;
      resource = this.getBaseUrl() + "resources/";
      return resource;
    };

    return Configs;

  })();
  return App.classrooms.configs = new Configs();
})($, window, document);
