// Generated by CoffeeScript 1.7.1
var App;

App = window.App || {};

App.classrooms = App.classrooms || {};

(function($, window, document) {
  var AnnouncementServices;
  AnnouncementServices = (function() {
    function AnnouncementServices() {
      this.isInitial = true;
      this.baseUrl = window.location.pathname;
    }

    AnnouncementServices.prototype.getAnnouncements = function() {
      var defer;
      defer = $.Deferred();
      if (this.isInitial === true) {
        defer.resolve(App.classrooms.announcements.data);
      }
      return defer.promise();
    };

    AnnouncementServices.prototype.getData = function(url) {
      var ajax;
      ajax = $.ajax({
        url: url,
        method: 'GET'
      });
      return ajax;
    };

    AnnouncementServices.prototype.postData = function(url, data) {
      var ajax;
      ajax = $.ajax({
        type: 'POST',
        url: url,
        data: data
      });
      return ajax;
    };

    AnnouncementServices.prototype.newClassroom = function(data) {
      return this.postData(this.baseUrl + '/add.json', data);
    };

    AnnouncementServices.prototype.getAnnouncementsByPage = function(page) {
      return this.getData(this.baseUrl + '/getannouncements.json?page=' + page);
    };

    AnnouncementServices.prototype.isValid = function(data) {
      return (data != null) && data.length > 0;
    };

    AnnouncementServices.prototype.getCurrentPage = function() {
      var url;
      url = window.location.href.split("/");
      return _.last(url);
    };

    return AnnouncementServices;

  })();
  return App.classrooms.announcementServices = new AnnouncementServices();
})($, window, document);
