// Generated by CoffeeScript 1.7.1
var App;

App = window.App || {};

App.classrooms = App.classrooms || {};

(function($, window, document) {
  var LibraryServices;
  LibraryServices = (function() {
    function LibraryServices() {
      this.isInitial = true;
      this.baseUrl = window.location.pathname;
    }

    LibraryServices.prototype.getLibraries = function() {
      var defer;
      defer = $.Deferred();
      if (this.isInitial === true) {
        defer.resolve(App.classrooms.libraries.data);
      }
      return defer.promise();
    };

    LibraryServices.prototype.getData = function(url) {
      var ajax;
      ajax = $.ajax({
        url: url,
        method: 'GET'
      });
      return ajax;
    };

    LibraryServices.prototype.postData = function(url, data) {
      var ajax;
      ajax = $.ajax({
        type: 'POST',
        url: url,
        data: data
      });
      return ajax;
    };

    LibraryServices.prototype.newClassroom = function(data) {
      return this.postData(this.baseUrl + '/add.json', data);
    };

    LibraryServices.prototype.getAnnouncementsByPage = function(page) {
      return this.getData(this.baseUrl + '/getannouncements.json?page=' + page);
    };

    LibraryServices.prototype.isValid = function(data) {
      return (data != null) && data.length > 0;
    };

    LibraryServices.prototype.getCurrentPage = function() {
      var url;
      url = window.location.href.split("/");
      return _.last(url);
    };

    return LibraryServices;

  })();
  return App.classrooms.libraryServices = new LibraryServices();
})($, window, document);
