// Generated by CoffeeScript 1.7.1
(function() {
  var App;

  App = window.App || {};

  App.classrooms = App.classrooms || {};

  (function($, window, document) {
    var Services;
    Services = (function() {
      function Services() {
        this.isInitial = true;
        this.baseUrl = '/PDD/pyoopil/Classrooms/';
      }

      Services.prototype.getClassrooms = function() {
        var defer;
        defer = $.Deferred();
        if (this.isInitial === true) {
          defer.resolve(App.classrooms.data);
        }
        return defer.promise();
      };

      Services.prototype.getData = function(url) {
        var ajax;
        ajax = $.ajax({
          url: url,
          method: 'GET'
        });
        return ajax;
      };

      Services.prototype.postData = function(url, data) {
        var ajax;
        ajax = $.ajax({
          type: 'POST',
          url: url,
          data: data
        });
        return ajax;
      };

      Services.prototype.newClassroom = function(data) {
        return this.postData(this.baseUrl + 'add.json', data);
      };

      Services.prototype.newJoinClassroom = function(data) {
        return this.postData(this.baseUrl + 'join.json', data);
      };

      Services.prototype.getClassroomsByPage = function(page) {
        return this.getData(this.baseUrl + 'getclassrooms.json?page=' + page);
      };

      Services.prototype.isValid = function(data) {
        return (data != null) && data.length > 0;
      };

      return Services;

    })();
    return App.classrooms.services = new Services();
  })($, window, document);

}).call(this);
