// Generated by CoffeeScript 1.7.1
var App;

App = window.App || {};

App.classrooms = App.classrooms || {};

(function($, window, document) {
  var Services;
  Services = (function() {
    function Services() {
      this.isInitial = true;
    }

    Services.prototype.getClassrooms = function() {
      var defer;
      defer = $.Deferred();
      if (this.isInitial === true) {
        defer.resolve(App.classrooms.data);
      }
      return defer.promise();
    };

    return Services;

  })();
  return App.classrooms.services = new Services();
})($, window, document);
