// Generated by CoffeeScript 1.7.1
angular.module('classrooms.services', []);

angular.module('classrooms.controllers', []);

angular.module('classrooms.directives', []);

angular.module('classrooms.filters', []);

angular.module('classrooms', ['classrooms.services', 'classrooms.controllers', 'classrooms.directives', 'classrooms.filters']);
