// Generated by CoffeeScript 1.7.1
var App;

App = window.App || {};

App.classrooms = App.classrooms || {};

(function($, window, document) {
  var $document, Classroom;
  $document = $(document);
  Classroom = (function() {
    function Classroom() {
      this.init();
      this.setEventListeners();
      this.getClassroomsData();
    }

    Classroom.prototype.init = function() {
      this.$createClassroomForm = $('#classroom-form');
      return this.$joinClassroom = $('#join-with-code');
    };

    Classroom.prototype.getClassroomsData = function() {
      var promise;
      promise = App.classrooms.services.getClassrooms();
      return promise.then(function(data) {
        return $document.trigger('Classrooms.dataReceived', [data]);
      });
    };

    Classroom.prototype.setEventListeners = function() {
      $document.on('Classrooms.dataReceived', App.classrooms.views.renderClassrooms);
      $document.on('Classrooms.newCreated', App.classrooms.views.newClassroom);
      $document.on('Classrooms.newJoin', App.classrooms.views.newJoin);
      this.$createClassroomForm.on('submit', this.newClassroomSubmit);
      return this.$joinClassroom.on('submit', this.joinClassroomSubmit);
    };

    Classroom.prototype.newClassroomSubmit = function(e) {
      var ajax;
      e.preventDefault();
      ajax = $.ajax({
        type: 'POST',
        url: 'Classrooms/add.json',
        data: $(this).serialize()
      });
      return ajax.done(function(data) {
        $document.trigger('Classrooms.newCreated', [data]);
        return $document.trigger('Classrooms.dataReceived', [[data]]);
      });
    };

    Classroom.prototype.joinClassroomSubmit = function(e) {
      var ajax;
      e.preventDefault();
      ajax = $.ajax({
        type: 'POST',
        url: 'Classrooms/join.json',
        data: $(this).serialize()
      });
      return ajax.done(function(data) {
          if(data.status){
              $document.trigger('Classrooms.newJoin', [data]);
              return $document.trigger('Classrooms.dataReceived', [[data]]);
          }
          else{
              //throw toast with message = data.message
          }
      });
    };

    return Classroom;

  })();
  return App.classrooms.classroom = new Classroom();
})($, window, document);
