// Generated by CoffeeScript 1.7.1
var App;

App = window.App || {};

App.LeftNavScroll = App.LeftNavScroll || {};

(function($, window, document) {
  var $document, LeftNav;
  $document = $(document);
  LeftNav = (function() {
    function LeftNav() {
      this.setEventHandlers();
    }

    LeftNav.prototype.setEventHandlers = function() {
      return $document.on('Classrooms.dataReceived', App.LeftNavScroll.views.renderClassrooms);
    };

    return LeftNav;

  })();
  return App.LeftNavScroll.leftNav = new LeftNav();
})($, window, document);
