// Generated by CoffeeScript 1.7.1
var App;

App = window.App || {};

App.LeftNavScroll = App.LeftNavScroll || {};

(function($, window, document) {
  var Services;
  Services = (function() {
    function Services() {
      this.isInitial = true;
    }

    Services.prototype.getClassrooms = function() {
      var defer;
      defer = $.Deferred();
      if (this.isInitial === true) {
        defer.resolve(App.leftNavData);
      }
      return defer.promise();
    };

    Services.prototype.isValid = function(data) {
      return (data != null) && data.length > 0;
    };

    return Services;

  })();
  return App.LeftNavScroll.services = new Services();
})($, window, document);
