// Generated by CoffeeScript 1.7.1
(function() {
  var App;

  App = window.App || {};

  App.common = App.common || {};

  (function($, window, document) {
    var $document, Notifier;
    $document = $(document);
    Notifier = (function() {
      function Notifier() {
        toastr.options = {
          "closeButton": true,
          "positionClass": "toast-top-full-width",
          "onclick": null,
          "showDuration": "300",
          "hideDuration": "1000",
          "timeOut": "5000",
          "extendedTimeOut": "1000"
        };
        this.notifier = toastr;
      }

      Notifier.prototype.notify = function(type, message) {
        return this.notifier[type](message);
      };

      return Notifier;

    })();
    return App.common.notifier = new Notifier;
  })($, window, document);

}).call(this);
