// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Classrooms').directive('classroomHeader', [
    'Utilities', 'mainService', function(Utilities, mainService) {
      return {
        restrict: 'E',
        replace: true,
        scope: {},
        templateUrl: '/pyoopil/js/app/partials/classrooms/header.html',
        link: function(scope, elem, attrs) {
          var $create, xhr;
          scope.showModal = false;
          $create = elem.find('#newClassroom');
          xhr = mainService.getClassrooms();
          xhr.then(function(data) {
            return console.log(data);
          });
          return $create.on('click', function(e) {
            Utilities.openModal('create-classroom-form.html');
            return false;
          });
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=classroom-header.map
