// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Controllers').controller('mainCtrl', [
    '$scope', 'Utilities', 'Auth', '$state', 'mainService', function($scope, Utilities, Auth, $state, mainService) {
      $scope.template = {};
      $scope.showModal = false;
      $scope.classroom = {
        campus_id: 1,
        department_id: 1,
        duration_start_date: '06/21/2014',
        duration_end_date: '06/21/2014',
        semester: 1,
        is_private: 0,
        description: 'Description',
        degree_id: 1
      };
      Utilities.init($scope);
      return $scope.newClassroom = function(form) {
        var data, promise;
        if ($scope.classroom.title == null) {
          toastr.error('Please enter a classroom name');
          return false;
        }
        data = {
          "Classroom": $scope.classroom
        };
        promise = mainService.newClassroom(data);
        return promise.then(function(data) {
          var template;
          console.log(data);
          toastr.success('Classroom Successfully Created');
          if ($scope.classroom.is_private === 0) {
            template = 'public-classroom-success-message.html';
          } else {
            $scope.code = data.data.data.Classroom.access_code;
            template = 'private-classroom-success-message.html';
          }
          Utilities.openModal(template);
          return $scope.$broadcast('Classroom.CREATE', data.data);
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=mainCtrl.map
