// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('Pyoopil.Services', []);

  angular.module('Pyoopil.Controllers', []);

  angular.module('Pyoopil.Directives', []);

  angular.module('Pyoopil.Filters', []);

  angular.module('pyoopil', ['Pyoopil.Services', 'Pyoopil.Controllers', 'Pyoopil.Directives', 'Pyoopil.Filters', 'ui.router', 'reCAPTCHA']).config([
    '$stateProvider', '$locationProvider', '$urlRouterProvider', function($stateProvider, $locationProvider, $urlRouterProvider) {
      $stateProvider.state('index', {
        url: '/index',
        templateUrl: 'js/app/partials/landing.html'
      }).state('login', {
        url: '/login',
        templateUrl: '/pyoopil/js/app/partials/modules/landing.html'
      }).state('login.Classrooms', {
        url: '/Classrooms',
        views: {
          'nav': {
            templateUrl: '/pyoopil/js/app/partials/modules/leftNav.html'
          },
          'viewport': {
            templateUrl: '/pyoopil/js/app/partials/Classrooms/landing.html',
            controller: 'classroomCtrl'
          }
        }
      }).state('login.Classroom', {
        url: '/Classroom/:id',
        views: {
          'nav': {
            templateUrl: '/pyoopil/js/app/partials/modules/leftNav.html'
          },
          'viewport': {
            templateUrl: '/pyoopil/js/app/partials/Classrooms/classroom.html',
            controller: 'announcementCtrl'
          }
        }
      }).state('reset', {
        url: '/reset',
        templateUrl: '/pyoopil/js/app/partials/reset-password.html'
      }).state('logout', {
        url: '/logout',
        templateUrl: '/pyoopil/js/app/partials/logout.html',
        controller: 'logoutCtrl'
      });
      return $urlRouterProvider.otherwise('index');
    }
  ]).config([
    'reCAPTCHAProvider', function(reCAPTCHAProvider) {
              //$http.defaults.useXDomain = true;
      return reCAPTCHAProvider.setPublicKey('6LeO9fcSAAAAAMsp8vSGpYd8ZHDdcHxvXrZHGf6q');
    }
  ]).run([
    '$rootScope', '$state', '$stateParams', 'Auth', function($rootScope, $state, $stateParams, Auth) {
      return $rootScope.$on('$stateChangeStart', function(e, toState, toStateParams, fromState, fromStateParams) {
        $rootScope.toState = toState;
        $rootScope.toStateParams = toStateParams;
        if (toState.name === 'index') {
          if (Auth.isLoggedIn()) {
            $state.go('login.Classrooms');
            return;
          }
          return;
        } else {
          if (!Auth.isLoggedIn()) {
            $state.go('index');
          }
        }
        return false;
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=app.map
