git rm app/webroot/css/aashi.css
git rm app/webroot/css/cake.generic.css
git rm app/webroot/css/tinyeditor.css
git rm app/webroot/images/cake.icon.png
git rm app/webroot/images/cake.power.gif
git rm app/webroot/images/calender.png
git rm app/webroot/images/classroom/images/005_Classrooms_people_01.jpg
git rm app/webroot/images/classroom/images/005_Classrooms_people_02.jpg
git rm app/webroot/images/classroom/images/005_Classrooms_people_04.jpg
git rm app/webroot/images/classroom/images/005_Classrooms_people_05.jpg
git rm app/webroot/images/classroom/images/006_Classrooms_submissions_01.jpg
git rm app/webroot/images/classroom/images/006_Classrooms_submissions_02.jpg
git rm app/webroot/images/classroom/images/006_Classrooms_submissions_04.jpg
git rm app/webroot/images/classroom/images/006_Classrooms_submissions_05.jpg
git rm app/webroot/images/classroom/images/007_Classrooms_engagement_01.jpg
git rm app/webroot/images/classroom/images/007_Classrooms_engagement_02.jpg
git rm app/webroot/images/classroom/images/007_Classrooms_engagement_04.jpg
git rm app/webroot/images/classroom/images/007_Classrooms_engagement_05.jpg
git rm app/webroot/images/classroom/images/ans-radio.png
git rm app/webroot/images/classroom/images/ans-radio1.png
git rm app/webroot/images/classroom/images/following11-1-_01.png
git rm app/webroot/images/classroom/images/following11-1-_02.png
git rm app/webroot/images/classroom/images/following11-1-_04.png
git rm app/webroot/images/classroom/images/following11-1-_05.png
git rm app/webroot/images/classroom/images/pop-check.png
git rm app/webroot/images/classroom/images/pop-check1.png
git rm app/webroot/images/classroom/images/time-check.png
git rm app/webroot/images/classroom/images/time-check1.png
git rm app/webroot/images/corridor_bar_icons.png
git rm app/webroot/images/country-flags/Aland.png
git rm app/webroot/images/country-flags/Andorra_flat.png
git rm app/webroot/images/country-flags/india-mini.jpg
git rm app/webroot/images/de.png
git rm app/webroot/images/fr.png
git rm app/webroot/images/images/006-POP-up-1_01.png
git rm app/webroot/images/images/006-POP-up-1_02.png
git rm app/webroot/images/images/006-POP-up-1_03.png
git rm app/webroot/images/images/006-POP-up-1_04.png
git rm app/webroot/images/images/006-POP-up-1_05.png
git rm app/webroot/images/it.png
git rm app/webroot/images/landing/dfgd.png
git rm app/webroot/images/no-praise.png
git rm app/webroot/images/nopoint-icon.png
git rm app/webroot/images/online.png
git rm app/webroot/images/point-icon.png
git rm app/webroot/images/praise-icon.png
git rm app/webroot/images/prettyPhoto/sd1.png
git rm app/webroot/images/prettyPhoto/sdss1.png
git rm app/webroot/images/prettyPhoto/sprite_next.png
git rm app/webroot/images/prettyPhoto/sprite_prev.png
git rm app/webroot/images/test-error-icon.png
git rm app/webroot/images/test-fail-icon.png
git rm app/webroot/images/test-pass-icon.png
git rm app/webroot/images/test-skip-icon.png
git rm app/webroot/images/us.png
git rm app/webroot/js/empty
git rm app/webroot/js/pyoopilcore.js
git rm app/webroot/js/tiny.editor.js
